# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='',
  serialized_pb=_b('\n\trpc.proto\"C\n\x04Node\x12\n\n\x02ip\x18\x01 \x02(\t\x12\x0c\n\x04port\x18\x02 \x02(\r\x12\x0e\n\x06nodeid\x18\x03 \x02(\t\x12\x11\n\tpublickey\x18\x04 \x01(\x0c\"\x06\n\x04Ping\"\x06\n\x04Pong\"#\n\x05Store\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\x17\n\x08\x46indNode\x12\x0b\n\x03key\x18\x01 \x02(\t\",\n\x10\x46indNodeResponse\x12\x18\n\tneighbors\x18\x01 \x03(\x0b\x32\x05.Node\"\xe0\x01\n\x07Message\x12\x15\n\x06sender\x18\x01 \x02(\x0b\x32\x05.Node\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\r\n\x05nonce\x18\x03 \x02(\x04\x12\x15\n\x04ping\x18\x04 \x01(\x0b\x32\x05.PingH\x00\x12\x15\n\x04pong\x18\x05 \x01(\x0b\x32\x05.PongH\x00\x12\x17\n\x05store\x18\x06 \x01(\x0b\x32\x06.StoreH\x00\x12\x1d\n\x08\x66indNode\x18\x07 \x01(\x0b\x32\t.FindNodeH\x00\x12-\n\x10\x66indNodeResponse\x18\x08 \x01(\x0b\x32\x11.FindNodeResponseH\x00\x42\x07\n\x05inner')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='Node.ip', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='Node.port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeid', full_name='Node.nodeid', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publickey', full_name='Node.publickey', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=80,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=88,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=96,
)


_STORE = _descriptor.Descriptor(
  name='Store',
  full_name='Store',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Store.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Store.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=133,
)


_FINDNODE = _descriptor.Descriptor(
  name='FindNode',
  full_name='FindNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='FindNode.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=158,
)


_FINDNODERESPONSE = _descriptor.Descriptor(
  name='FindNodeResponse',
  full_name='FindNodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neighbors', full_name='FindNodeResponse.neighbors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=204,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='Message.sender', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Message.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='Message.nonce', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ping', full_name='Message.ping', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pong', full_name='Message.pong', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='store', full_name='Message.store', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='findNode', full_name='Message.findNode', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='findNodeResponse', full_name='Message.findNodeResponse', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='inner', full_name='Message.inner',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=207,
  serialized_end=431,
)

_FINDNODERESPONSE.fields_by_name['neighbors'].message_type = _NODE
_MESSAGE.fields_by_name['sender'].message_type = _NODE
_MESSAGE.fields_by_name['ping'].message_type = _PING
_MESSAGE.fields_by_name['pong'].message_type = _PONG
_MESSAGE.fields_by_name['store'].message_type = _STORE
_MESSAGE.fields_by_name['findNode'].message_type = _FINDNODE
_MESSAGE.fields_by_name['findNodeResponse'].message_type = _FINDNODERESPONSE
_MESSAGE.oneofs_by_name['inner'].fields.append(
  _MESSAGE.fields_by_name['ping'])
_MESSAGE.fields_by_name['ping'].containing_oneof = _MESSAGE.oneofs_by_name['inner']
_MESSAGE.oneofs_by_name['inner'].fields.append(
  _MESSAGE.fields_by_name['pong'])
_MESSAGE.fields_by_name['pong'].containing_oneof = _MESSAGE.oneofs_by_name['inner']
_MESSAGE.oneofs_by_name['inner'].fields.append(
  _MESSAGE.fields_by_name['store'])
_MESSAGE.fields_by_name['store'].containing_oneof = _MESSAGE.oneofs_by_name['inner']
_MESSAGE.oneofs_by_name['inner'].fields.append(
  _MESSAGE.fields_by_name['findNode'])
_MESSAGE.fields_by_name['findNode'].containing_oneof = _MESSAGE.oneofs_by_name['inner']
_MESSAGE.oneofs_by_name['inner'].fields.append(
  _MESSAGE.fields_by_name['findNodeResponse'])
_MESSAGE.fields_by_name['findNodeResponse'].containing_oneof = _MESSAGE.oneofs_by_name['inner']
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['Store'] = _STORE
DESCRIPTOR.message_types_by_name['FindNode'] = _FINDNODE
DESCRIPTOR.message_types_by_name['FindNodeResponse'] = _FINDNODERESPONSE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Node)
  ))
_sym_db.RegisterMessage(Node)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Ping)
  ))
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), dict(
  DESCRIPTOR = _PONG,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Pong)
  ))
_sym_db.RegisterMessage(Pong)

Store = _reflection.GeneratedProtocolMessageType('Store', (_message.Message,), dict(
  DESCRIPTOR = _STORE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Store)
  ))
_sym_db.RegisterMessage(Store)

FindNode = _reflection.GeneratedProtocolMessageType('FindNode', (_message.Message,), dict(
  DESCRIPTOR = _FINDNODE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:FindNode)
  ))
_sym_db.RegisterMessage(FindNode)

FindNodeResponse = _reflection.GeneratedProtocolMessageType('FindNodeResponse', (_message.Message,), dict(
  DESCRIPTOR = _FINDNODERESPONSE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:FindNodeResponse)
  ))
_sym_db.RegisterMessage(FindNodeResponse)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
